#!/bin/bash

sh ~/.config/xrandr/main.sh
bspc monitor DP-4 -d 1 2 3 4 5 6

bspc config border_width 2
#bspc config focused_border_color "#3B4252"
bspc config focused_border_color "#DDDDDD"
bspc config normal_border_color "#282e3a"

nm-applet 2>&1 >/dev/null &
blueman-applet 2>&1 >/dev/null &
