#!/bin/bash

#bspc monitor -d TERM WEB CODE MISC EDIT CHAT DISCORD MUSIC
xrandr --output DP-4 --mode 3440x1440 --rate 144
bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9 0
#for i in $(bspc query -D --names)
#do
#    bsp-layout set tall $i -- --master-size 0.65 &
#done

bspc config border_width         2
#bspc config focused_border_color "#3B4252"
bspc config focused_border_color "#DDDDDD"
bspc config normal_border_color "#282e3a"

nm-applet 2>&1 > /dev/null &
blueman-applet 2>&1 > /dev/null &
