#!/bin/bash

num_displays=$(xrandr --listmonitors | grep -v "Monitors:" | wc -l)
if [ $num_displays -eq 1 ]; then
	# If only one display is connected, set 10 workspaces on it
	sh ~/.screenlayout/1.sh
	bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
else
	# If multiple displays are connected, set 5 workspaces on each
	sh ~/.screenlayout/2.sh
	bspc monitor DP-2 -d 1 2 3 4 5 6 7
	bspc monitor eDP-1 -d 8 9 10
fi

bspc config border_width 2
#bspc config focused_border_color "#3B4252"
bspc config focused_border_color "#DDDDDD"
bspc config normal_border_color "#282e3a"

nm-applet 2>&1 >/dev/null &
blueman-applet 2>&1 >/dev/null &
