#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

setxkbmap -layout 'us,ru' -option 'grp:win_space_toggle'
xsetroot -cursor_name left_ptr &
sxhkd &
picom &
eval "$(ssh-agent -s)"
dunst &

MONITOR=""
MONITOR2=""
# laptop
if [ "$(hostname)" == "arcashka-Latitute-5531" ]; then
	num_displays=$(xrandr --listmonitors | grep -v "Monitors:" | wc -l)
	if [ $num_displays -eq 1 ]; then
		MONITOR="eDP-1"
		sh $HOME/.config/bspwm/screenlayouts/laptop.sh
	else
		MONITOR="DP-2"
		MONITOR2="eDP-1"
		sh $HOME/.config/bspwm/screenlayouts/laptop_with_monitor.sh
	fi
# pc
elif [ "$(hostname)" == "arcashka-pc" ]; then
	MONITOR="DP-4"
	$HOME/.config/bspwm/screenlayouts/pc.sh
fi

if [ -z "$MONITOR2" ]; then
	sed "s/__MONITOR__/$MONITOR/g" ~/.config/polybar/config.template >/tmp/polybar-config
	bspc monitor ${MONITOR} -d 1 2 3 4 5 6 7 8 9 0
	polybar example -c /tmp/polybar-config &
else
	sed -e "s/__MONITOR__/$MONITOR/g" -e "s/__MONITOR2__/$MONITOR2/g" ~/.config/polybar/config.template >/tmp/polybar-config
	bspc monitor ${MONITOR} -d 1 2 3 4 5 6 7
	bspc monitor ${MONITOR2} -d 8 9 0
	polybar secondary -c /tmp/polybar-config &
fi

bspc config border_width 2
#bspc config focused_border_color "#3B4252"
bspc config focused_border_color "#DDDDDD"
bspc config normal_border_color "#282e3a"

nm-applet 2>&1 >/dev/null &
blueman-applet 2>&1 >/dev/null &

nitrogen --restore
bspc rule --add program state=floating rectangle=WxH+X+Y
bspc config window_gap 20
bspc config split_ratio 1
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a telegram-desktop state=floating
